appname="彩虹糖"
appver="2.1"
appcode="5201314"
appsdk="21"
path_pattern=""
packagename="com.CottonCandy"
theme="Theme_Material_Light_NoActionBar"
developer=""
description=""
debugmode=false
user_permission={
  "CHANGE_NETWORK_STATE",
  "DOWNLOAD_WITHOUT_NOTIFICATION",
  "GET_PACKAGE_SIZE",
  "INTERNET",
  "READ_EXTERNAL_STORAGE",
  "READ_PHONE_STATE",
  "SET_WALLPAPER",
  "WRITE_EXTERNAL_STORAGE",
  "WRITE_SETTINGS"
}
